### ISSUE TITLE
sim dataset

### ISSUE THREAD

**Issue by LeiWangCV** [jaycions/activezero2_official#1]
Hello, thank you for your open source code. I would like to follow up on this work, but an error occurred while rendering the data: FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sda/activezero/mini-imagenet/mini_imagenet_ist. txt'.
I still don't quite understand how this dataset is rendered. Can you please help me with this.

**Comment by jaycions** [comment]
Sorry for the late response. Have you solved the problem? When we render the sim dataset, we may use the images from mini-imagenet as the texture for rendered objects. The error shows the lack of "mini-imagenet" files. You can download it from the internet. If you meet any questions about activezero++ and do not know how to solve it, please contact me with my wechat 13645098682. I will help you.
